New engine to Generate and Print Thermal Receipt Through Adyen Android Terminals
CHEQPlease/Flutter-Adyen-Terminal pull request #1
Opened 2023-01-13 09:35 UTC by itsniaz

2023-01-13 18:01 UTC, rkmohajan requested changes

2023-01-13 18:01 UTC, rkmohajan commented on android/src/main/kotlin/com/itsniaz/adyen/adyen_terminal_payment/AdyenTerminalManager.kt
> +import com.itsniaz.adyen.adyen_terminal_payment.receipt.ReceiptBuilder
The library should be 

com.adyen.*

2023-01-13 18:13 UTC, itsniaz commented on android/src/main/kotlin/com/itsniaz/adyen/adyen_terminal_payment/AdyenTerminalManager.kt
> +import com.itsniaz.adyen.adyen_terminal_payment.receipt.ReceiptBuilder
It should actually be com.cheqplease.adyen.* something like this since it is not from adyen.

Started it on my own GitHub account on my personal time thinking of opensourcing it on pub.dev.

Later transferred the ownership to CHEQPlease when it was a requiment for the project and needed further development.

** Will update the PR with updated package name

2023-01-13 18:15 UTC, rkmohajan commented on android/src/main/kotlin/com/itsniaz/adyen/adyen_terminal_payment/AdyenTerminalManager.kt
> +import com.itsniaz.adyen.adyen_terminal_payment.receipt.ReceiptBuilder
Make sense.

2023-01-30 08:33 UTC, rkmohajan commented on android/settings.gradle
> +rootProject.name = 'flutter_adyen_terminal'
Should it be adyen_terminal only ? 

as the  package="com.cheqplease.adyen_terminal"

2023-01-30 08:33 UTC, itsniaz commented on android/src/main/kotlin/com/itsniaz/adyen/adyen_terminal_payment/AdyenTerminalManager.kt
> +import com.itsniaz.adyen.adyen_terminal_payment.receipt.ReceiptBuilder
Changed the package name to com.cheqplease.adyen_terminal

2023-02-03 11:03 UTC, itsniaz commented
@rkmohajan Please finish the review asap, Need to merge it with main

2023-02-03 14:17 UTC, faisalcheq approved these changes
We have reviewed in group call.
Looks good to us.
cc : @rkmohajan Bhai @project-lambda bhai @shafiur-rahman Bhai

2023-02-03 14:20 UTC, project-lambda approved these changes
Looks Good to me

2023-02-03 14:21 UTC, merged